# Generated by Django 3.2.22 on 2023-10-21 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buscar_estacionamiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dueno',
            name='apellido',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arrendamiento',
            name='hora_fin',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='arrendamiento',
            name='hora_inicio',
            field=models.TimeField(default='00:00'),
        ),
    ]
