# Generated by Django 3.2.22 on 2023-10-21 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscar_estacionamiento', '0002_auto_20231021_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacionamiento',
            name='capacidad',
        ),
    ]
