# Generated by Django 3.2.22 on 2023-10-22 19:54

from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('buscar_estacionamiento', '0005_alter_estacionamiento_costo_por_hora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comuna',
            old_name='comuna',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='estacionamiento',
            old_name='dueño',
            new_name='dueno',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='vehiculo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='contraseña',
            field=models.CharField(default=django.utils.crypto.get_random_string, max_length=8),
        ),
        migrations.AddField(
            model_name='cliente',
            name='vehiculos',
            field=models.ManyToManyField(blank=True, related_name='clientes_vehiculos', to='buscar_estacionamiento.Vehiculo'),
        ),
        migrations.AddField(
            model_name='dueno',
            name='contraseña',
            field=models.CharField(default=django.utils.crypto.get_random_string, max_length=8),
        ),
        migrations.AddField(
            model_name='dueno',
            name='estacionamientos',
            field=models.ManyToManyField(blank=True, related_name='duenos_estacionamientos', to='buscar_estacionamiento.Estacionamiento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='dueno',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='costo_por_hora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
