# Generated by Django 3.2.22 on 2023-10-22 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buscar_estacionamiento', '0006_auto_20231022_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comuna',
            old_name='nombre',
            new_name='comuna',
        ),
        migrations.RenameField(
            model_name='estacionamiento',
            old_name='dueno',
            new_name='dueño',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='vehiculos',
        ),
        migrations.RemoveField(
            model_name='dueno',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='dueno',
            name='estacionamientos',
        ),
        migrations.AddField(
            model_name='reporte',
            name='vehiculo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='buscar_estacionamiento.vehiculo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='dueno',
            name='rut',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='costo_por_hora',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(max_length=7),
        ),
    ]
