# Generated by Django 3.2.22 on 2023-10-24 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscar_estacionamiento', '0008_auto_20231022_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='email',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='dueno',
            old_name='email',
            new_name='username',
        ),
    ]
