# Generated by Django 3.2.22 on 2023-10-14 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=12)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dueno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=12)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=254, null=True)),
                ('comuna_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=200)),
                ('capacidad', models.IntegerField()),
                ('dueño_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.dueno')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=7)),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('monto_recaudado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.cliente')),
                ('estacionamiento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.estacionamiento')),
                ('vehiculo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='comuna_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.comuna'),
        ),
        migrations.CreateModel(
            name='Arrendamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('precio', models.IntegerField()),
                ('hora_inicio', models.TimeField(default='00:00:00')),
                ('hora_fin', models.TimeField(default='00:00:00')),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.cliente')),
                ('estacionamiento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.estacionamiento')),
            ],
        ),
    ]
